# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/MicroBlaze_GPIO_Timer_Interrupt/MicroBlaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_Timer_Interrupt/ip/design_Timer_Interrupt_clk_wiz_1_0/design_Timer_Interrupt_clk_wiz_1_0.xci
# IP: The module: 'design_Timer_Interrupt_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/MicroBlaze_GPIO_Timer_Interrupt/MicroBlaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_Timer_Interrupt/ip/design_Timer_Interrupt_clk_wiz_1_0/design_Timer_Interrupt_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Timer_Interrupt_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/MicroBlaze_GPIO_Timer_Interrupt/MicroBlaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_Timer_Interrupt/ip/design_Timer_Interrupt_clk_wiz_1_0/design_Timer_Interrupt_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Timer_Interrupt_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/MicroBlaze_GPIO_Timer_Interrupt/MicroBlaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_Timer_Interrupt/ip/design_Timer_Interrupt_clk_wiz_1_0/design_Timer_Interrupt_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Timer_Interrupt_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/FPGA/MicroBlaze_GPIO_Timer_Interrupt/MicroBlaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_Timer_Interrupt/ip/design_Timer_Interrupt_clk_wiz_1_0/design_Timer_Interrupt_clk_wiz_1_0.xci
# IP: The module: 'design_Timer_Interrupt_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/MicroBlaze_GPIO_Timer_Interrupt/MicroBlaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_Timer_Interrupt/ip/design_Timer_Interrupt_clk_wiz_1_0/design_Timer_Interrupt_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Timer_Interrupt_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/MicroBlaze_GPIO_Timer_Interrupt/MicroBlaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_Timer_Interrupt/ip/design_Timer_Interrupt_clk_wiz_1_0/design_Timer_Interrupt_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Timer_Interrupt_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/MicroBlaze_GPIO_Timer_Interrupt/MicroBlaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_Timer_Interrupt/ip/design_Timer_Interrupt_clk_wiz_1_0/design_Timer_Interrupt_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Timer_Interrupt_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
